import type { Metadata } from "next";
import Link from "next/link";
import getAllUsers from "../../libs/getAllUsers";

export const metadata: Metadata = {
  title: "Next Js Users Page",
  description: "Generated by create next app",
};

import React from "react";

export default async function Users() {
  const userData: Promise<User[]> = getAllUsers();
  const users = await userData;
  
  const content = (
    <section>
      <h2>
        <Link href={"/"}>Back to Home</Link>
      </h2>
      <br />
      {users.map((user) => {
        return (
          <>
            <p key={user.id}>
              <Link href={`/users/${user.id}`}>{user.name}</Link>
            </p>
            <br />
          </>
        );
      })}
    </section>
  );

  return content;
}
