import React from "react";
import type { Metadata } from "next";
import css from "./style.module.css";

export const metadata: Metadata = {
  title: "Next Js About Page",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <nav>
        <h1>About Navbar</h1>
      </nav>
      <main className={css.main}>{children}</main>
    </>
  );
}
